# Generated by Django 5.2.12 on 2026-04-29 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('kg_bought', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cost_price_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manual_profit_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chicken', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('crate_wt', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('no_of_crates', models.IntegerField(default=1)),
                ('birds_per_crate', models.IntegerField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('group_no', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
    ]
