services:
  - type: web
    name: billing
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && gunicorn pos_system.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
